INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.1  สถานการณ์โรคและภัยสุขภาพที่สำคัญ + สิ่งแวดล้อม : กลุ่มงานบริการด้านปฐมภูมิและองค์รวม', 'ให้เสนอข้อมูลสถานการณ์โรคและภัยสุขภาพที่สำคัญ เช่น ไข้เลือดออก เห็ดพิษ Leptospirosis \r\nหรือสิ่งแวดล้อมที่เป็นปัญหาในโรงพยาบาล', '', 'palliative_template.xlsx', 'uploads/meetings/palliative_template.xlsx', '2023-8-10 12:47:12');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.2 การบริหารทรัพยากรบุคคล : กลุ่มงานบริหารงานทั่วไป', 'ให้เสนอข้อมูลแผนบุคลากร(3 ปี) - ฝึกอบรม - การจ้าง - การลาออก – ความดีความชอบ –\r\nความก้าวหน้า และปัญหาสุขภาพ/การเงินของเจ้าหน้าที่', '', 'HDC - Consent Form.pdf', 'uploads/meetings/HDC - Consent Form.pdf', '2023-8-10 13:41:32');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.3 สถานะการเงินการคลัง : งานการเงิน', 'ให้เสนอข้อมูลสถานะการเงินการคลัง', '', 'CQI การเข้าถึงระยะไกล.pdf', 'uploads/meetings/CQI การเข้าถึงระยะไกล.pdf', '2023-8-10 12:05:10');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.4 กองทุนต่างๆ : กลุ่มงานประกันสุขภาพยุทธศาสตร์และสารสนเทศทางการแพทย์', 'ให้เสนอข้อมูลรายได้จากกองทุนที่สำคัญ ได้แก่ ผู้ป่วยใน, non uc, ประกันสังคม, พรบ., \r\nทันตกรรม แผนไทย กายภาพบำบัด และ PP อื่นที่ไม่รวมกองทุนที่กล่าวข้างต้น โดยให้แสดง\r\nข้อมูลเปรียบเทียบแผนกับผลงานที่ได', '', '', '', '2023-8-10 10:35:22');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.5 ค่าใช้จ่ายที่สำคัญ : กลุ่มงานบริหารงานทั่วไป', '▪ ให้เสนอข้อมูล ดังนี้ ค่าไฟฟ้า ค่าน้ำมัน ค่าซ่อมแซมรถยนต์ค่าวัตถุดิบโรงครัว ค่าวัสดุงานบ้าน/\r\nสำนักงาน ค่าหมึกพิมพ์ ยา LAB ค่าออกซิเจน โดยแสดงข้อมูลเป็นรายเดือนให้เห็นแนวโน้ม\r\nเพิ่มขึ้นหรือลดลง', '', 'COVID19.pdf', 'uploads/meetings/COVID19.pdf', '2023-8-10 13:46:36');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.6 ความก้าวหน้าแผนการลงทุน 43 ล้าน +งบค่าเสื่อม : กลุ่มงานประกันสุขภาพยุทธศาสตร์และ\r\nสารสนเทศทางการแพทย์\r', '▪ ให้เสนอข้อมูลแผนปัจจุบันและแผน 3 ปีข้างหน้า', '', '', '', '2023-8-9 14:25:50');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.7 ความก้าวหน้าการพัฒนาระบบเทคโนโลยีสารสนเทศ : งาน IT', '▪ ให้เสนอความก้าวหน้าในการพัฒนา tripleA, iclaim, backoffice, mBaseและอื่นๆ ที่สำคัญ', '', '', '', '0000-0-0 00:00:00');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.8 แผนปฏิบัติการ และการปรับแผนปฏิบัติการ : กลุ่มงานประกันสุขภาพยุทธศาสตร์และ\r\nสารสนเทศทางการแพทย์', '▪ ให้เสนอความก้าวหน้าการดำเนินงานตามแผนปฏิบัติการ รวมถึงการปรับแผนปฏิบัติการ', '', '', '', '0000-0-0 00:00:00');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.9 ความเสี่ยงที่สำคัญของโรงพยาบาล : ทีมความเสี่ยง', '▪ ให้เสนอข้อมูลข้อร้องเรียนต่างๆ เน้นความเสี่ยงระดับ E และข้อร้องเรียนด้านพฤติกรรมบริการ\r\nโดยระบุประเด็นพฤติกรรมบริการใด และเกิดขึ้นในหน่วยงานใด', '', '', '', '2023-8-10 10:35:28');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.10 งานพัฒนาคุณภาพสถานพยาบาล : สำนักคุณภาพ', '▪ ให้เสนอข้อมูลความก้าวหน้า หรือประเด็นสำคัญที่ต้องเร่งกำกับติดตามเพื่อให้การพัฒนาคุณภาพ\r\nเป็นไปอย่างต่อเนื่อง', '', '', '', '2023-8-9 14:29:20');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 3, '3.11 การปรับระบบบริการ: กลุ่มงานการพยาบาล', '▪ ให้เสนอข้อมูลการปรับระบบบริการในแต่ละจุด เช่น การบริการนอกเวลา การปรับระบบงาน\r\nร่วมกันระหว่างสหวิชาชีพ เป็นต้น', '', '', '', '2023-8-10 10:35:31');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '1. กลุ่มงานบริหารทั่วไป', '▪ ให้เสนอข้อมูลการปรับระบบบริการในแต่ละจุด เช่น การบริการนอกเวลา การปรับระบบงาน\r\nร่วมกันระหว่างสหวิชาชีพ เป็นต้นเด้อครับ5555', '', 'ประกาศรับสมัครสอบ ลว.3 สค.66.pdf', 'uploads/meetings/ประกาศรับสมัครสอบ ลว.3 สค.66.pdf', '2023-8-10 13:43:58');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '2. กลุ่มงานการพยาบาล', '', '', 'รพ.ม่วงสามสิบ คำสั่งแต่งตั้งคณะกรรมการ DI.pdf', 'uploads/meetings/รพ.ม่วงสามสิบ คำสั่งแต่งตั้งคณะกรรมการ DI.pdf', '2023-8-10 13:45:26');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '3.กลุ่มงานบริการด้านปฐมภูมิและองค์รวม', NULL, '', '', '', '0000-0-0 00:00:00');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '4. กลุ่มงานเทคนิคการแพทย์', '', '', '', '', '2023-8-9 15:30:43');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '5. กลุ่มงานเภสัชกรรมฯ', NULL, '', '', '', '2023-8-9 15:00:35');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '6. กลุ่มงานทันตกรรม', '', '', '', '', '2023-8-9 16:17:28');
INSERT INTO `agenda_subx` ( `meeting_id`, `agenda_id`, `sub_topic`, `sub_description`, `department`, `filename`, `path`, `create_date`) VALUES ( 0, 4, '7. กลุ่มงานบริการทางการแพทย์', '', '', '', '', '2023-8-9 15:32:12');

INSERT INTO `agenda_item` VALUES ( 1, 0, NULL, 'วาระที่1', 'ประธานแจ้งให้ทราบ', NULL, '', '2023-8-11 15:40:11', NULL);
INSERT INTO `agenda_item` VALUES ( 2, 0, NULL, 'วาระที่2', 'รับรองรายงานการประชุมครั้งที่ผ่านมา', NULL, '', '2023-8-11 15:40:15', NULL);
INSERT INTO `agenda_item` VALUES ( 3, 0, '', 'วาระที่3', 'ประเด็นสำคัญที่ติดตาม\r\n', '', '', '2023-8-11 15:40:18', NULL);
INSERT INTO `agenda_item` VALUES ( 4, 0, NULL, 'วาระที่4', 'เรื่องจากกลุ่มงาน', NULL, '', '2023-8-11 15:40:20', NULL);
INSERT INTO `agenda_item` VALUES ( 5, 0, NULL, 'วาระที่5', 'เรื่องอื่นๆ', NULL, '', '2023-8-11 15:40:23', NULL);

